### ISSUE TITLE
make `launchApp` public on AbstractJavaFxApplicationSupport

### ISSUE THREAD

**Issue by jangalinski** [roskenet/spring-javafx-examples#1]
I am trying to get a springboot/JavaFx application to run with kotlin.

but when I do

```
@SpringBootApplication
class MyApplication : AbstractJavaFxApplicationSupport()

fun main(args: Array<String>)  {
  AbstractJavaFxApplicationSupport.launchApp(MyApp::class.java, MyView::class.java, args)
}

```

I cannot access the `launchApp`method since it is of protected scope.

Could you change visibility to support this usecase? It's not very useful to have this one protected imho, since the original `launch` is public, so you are not really hiding implementation details ...

**Comment by roskenet** [comment]
Yes, you are absolutely right! Makes no real sense to narrow the scope.
Will do this.

**Comment by roskenet** [comment]
Closed here in favour of https://github.com/roskenet/springboot-javafx-support/issues/13
