### ISSUE TITLE
Adding other spring based components

### ISSUE THREAD

**Issue by pixelpshr** [roskenet/spring-javafx-examples#2]
This isn't an issue, but rather a question.
I'm trying to add an accessor for a HyperSQL database to the springboot-javafx example. (Based on this example: http://www.giantflyingsaucer.com/blog/?p=2934) But, my database classes are not being found by the FXMLController class. 

Can you help with an example of how to do this? 

Danke!
Thom

**Comment by roskenet** [comment]
Moved issue to springboot-javafx-support lib:

https://github.com/roskenet/springboot-javafx-support/issues/24
